In [9]:
import scipy
import seaborn
import matplotlib
#matplotlib inline

In [15]:
 import tensorflow.compat.v1 as tf  
tf.compat.v1.disable_eager_execution()

In [24]:
# declare two symbolic floating-point scalars
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
# create a simple symbolic expression using the add function
add = tf.add(a, b)
# bind 1.5 toa , 2.5 tob , and evaluate c
sess = tf.Session()
binding = {a: [1,2,3], b: 0.03}
c = sess.run(add, feed_dict=binding)
print(c)

[1.03 2.03 3.03]


In [19]:
add=tf.add?

Signature: tf.add(x, y, name=None)
Docstring:
Returns x + y element-wise.

Example usages below.

Add a scalar and a list:

>>> x = [1, 2, 3, 4, 5]
>>> y = 1
>>> tf.add(x, y)
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6],
dtype=int32)>

Note that binary `+` operator can be used instead:

>>> x = tf.convert_to_tensor([1, 2, 3, 4, 5])
>>> y = tf.convert_to_tensor(1)
>>> x + y
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6],
dtype=int32)>

Add a tensor and a list of same shape:

>>> x = [1, 2, 3, 4, 5]
>>> y = tf.constant([1, 2, 3, 4, 5])
>>> tf.add(x, y)
<tf.Tensor: shape=(5,), dtype=int32,
numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

**Warning**: If one of the inputs (`x` or `y`) is a tensor and the other is a
non-tensor, the non-tensor input will adopt (or get casted to) the data type
of the tensor input. This can potentially cause unwanted overflow or underflow
conversion.

For example,

>>> x = tf.constant([1, 2], dtype=tf.int8)
>>> y = [2**7 +